return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts_extend = { "ensure_installed" },
  opts = {
    ensure_installed = {
      "html-lsp",
      "prettier",
      "pyright",
      "isort",
      "gopls",
      "goimports",
      "gofumpt",
      "sqlfluff",
      "actionlint",
      "ansible-language-server",
      "ansible-lint",
      "antlers-language-server",
      "black",
      "bash-language-server",
      "blade-formatter",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "dot-language-server",
      "emmet-ls",
      "eslint_d",
      "hadolint",
      "intelephense",
      "php-debug-adapter",
      "phpcs",
      "php-cs-fixer",
      "pint",
      "pyright",
      "rustywind",
      "shellcheck",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
    },
  },
}
